apiVersion: "apps/v1"
kind: "Deployment"

metadata:
  name: "etcd-ui"

spec:
  selector:
    matchLabels:
      app: "etcd-ui"

  template:
    metadata:
      # namespace: "infrastructure"
      labels:
        app: "etcd-ui"

    spec:
      containers:
        - name: "etcd-ui"
          image: "evildecay/etcdkeeper"

          env:
            - name: ETCD_PEER_ADDRESS
              value: "http://etcd:2379"

          ports:
            - containerPort: 8080

---

apiVersion: "v1"
kind: "Service"

metadata:
  name: "etcd-ui"

spec:
  selector:
    app: "etcd-ui"
  
  ports:
    - protocol: "TCP"
      name: "rest"
      port: 8080
      targetPort: 8080
      nodePort: 30011

  type: "NodePort"