apiVersion: "apps/v1"
kind: "Deployment"

metadata:
  name: "registry-ui"

spec:
  selector:
    matchLabels:
      app: "registry-ui"

  template:
    metadata:
      namespace: "private-registry"
      labels:
        app: "registry-ui"

    spec:
      containers:
        - name: "registry-ui"
          image: "joxit/docker-registry-ui"
          
          env:
            - name: "DELETE_IMAGES" # Env var name
              valueFrom:
                configMapKeyRef:
                  name: "registry-ui-configmap" # Name of ConfigMap
                  key: "delete-images" # Name of key in ConfigMap 

            - name: "SHOW_CONTENT_DIGEST" # Env var name
              valueFrom:
                configMapKeyRef:
                  name: "registry-ui-configmap" # Name of ConfigMap
                  key: "show-content-digest" # Name of key in ConfigMap 

          ports:
            - containerPort: 80

---

apiVersion: "v1"
kind: "Service"

metadata:
  name: "registry-ui"

spec:
  selector:
    app: "registry-ui"
  
  ports:
    - protocol: "TCP"
      name: "access-port"
      port: 80
      targetPort: 80
      nodePort: 31321

  type: "NodePort"
