# apiVersion: "networking.k8s.io/v1"
# kind: "Ingress"

# metadata:
#   name: "minimal-ingress"
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: "/"
#     nginx.ingress.kubernetes.io/add-base-url: "true"

# spec:
#   rules:
#     - http:
#         paths:
#           - path: "/"
#             pathType: "Prefix"
#             backend:
#               service:
#                 name: "demo-app"
#                 port:
#                   number: 80


apiVersion: "networking.k8s.io/v1"
kind: "Ingress"

metadata:
  name: "minimal-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/add-base-url: "true"

spec:
  rules:
    - http:
        paths:
          - path: "/app"
            pathType: "Prefix"
            backend:
              service:
                name: "demo-app"
                port:
                  number: 80
