apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "nfs-elastic-data"
spec:
  storageClassName: "elasticsearch-nfs"
  mountOptions:
    - "nfsvers=3"
  capacity:
    storage: "300Gi"
  accessModes:
    - "ReadWriteMany"
  nfs:
    server: "k8s-cluster-i7" # Hostname or IP
    path: "/mnt/shared_nfs_storage/elasticsearch" # Make sure this path exists first (in server)

---

apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "elasticsearch-volume-claim"
spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: "elasticsearch-nfs"
  resources:
    requests:
      storage: "300Gi"

# ---

# apiVersion: "v1"
# kind: "PersistentVolumeClaim"
# metadata:
  # name: "elasticsearch-volume-claim"
# spec:
  # storageClassName: "microk8s-hostpath"
  # accessModes:
    # - "ReadWriteMany"
  # resources:
    # requests:
      # storage: "300Gi"
