apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "nfs-etcd-data"
spec:
  storageClassName: "etcd-nfs"
  mountOptions:
    - "nfsvers=3"
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  nfs:
    server: "k8s-cluster-i7" # Hostname or IP
    path: "/mnt/shared_nfs_storage/etcd" # Make sure this path exists first (in server)

---

apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "etcd-volume-claim"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "etcd-nfs"
  resources:
    requests:
      storage: "5Gi"
