apiVersion: "v1"
kind: "PersistentVolume"

metadata:
  name: "nfs-jenkins"
  namespace: "jenkins"

spec:
  storageClassName: "jenkins-nfs"
  mountOptions:
    - "nfsvers=3"
  capacity:
    storage: "20Gi"
  accessModes:
    - "ReadWriteOnce"
  nfs:
    server: "k8s-cluster-i7" # Hostname or IP
    path: "/mnt/shared_nfs_storage/jenkins" # Make sure this path exists first (in server)

---

apiVersion: "v1"
kind: "PersistentVolumeClaim"

metadata:
  name: "jenkins-volume-claim"
  namespace: "jenkins"

spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "jenkins-nfs"
  resources:
    requests:
      storage: "20Gi"