apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "hostpath-elastic-data"
spec:
  storageClassName: "elasticsearch-hostpath"
  capacity:
    storage: "100Gi"
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: "/data_backup/elasticsearch"

---

apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "elasticsearch-hostpath-claim"
spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: "elasticsearch-hostpath"
  resources:
    requests:
      storage: "100Gi"