apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  namespace: "private-registry"
  name: "nfs-private-registry-certs"

spec:
  storageClassName: "private-registry-certs-nfs"
  mountOptions:
    - "nfsvers=3"
  capacity:
    storage: "50Mi"
  accessModes:
    - "ReadWriteMany"
  nfs:
    server: "k8s-cluster-i7" # Hostname or IP
    path: "/mnt/shared_nfs_storage/private-registry/certs" # Make sure this path exists first (in server)

---

apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  namespace: "private-registry"
  name: "private-registry-certs-claim"

spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: "private-registry-certs-nfs"
  resources:
    requests:
      storage: "50Mi"

---

apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  namespace: "private-registry"
  name: "nfs-private-registry-data"
  
spec:
  storageClassName: "private-registry-data-nfs"
  mountOptions:
    - "nfsvers=3"
  capacity:
    storage: "150Gi"
  accessModes:
    - "ReadWriteMany"
  nfs:
    server: "k8s-cluster-i7" # Hostname or IP
    path: "/mnt/shared_nfs_storage/private-registry/registry" # Make sure this path exists first (in server)

---

apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  namespace: "private-registry"
  name: "private-registry-data-volume-claim"

spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: "private-registry-data-nfs"
  resources:
    requests:
      storage: "150Gi"
